### PR TITLE
Colgate Total Whitening Gel added

### PR DESCRIPTION
**Pull request by manaswinidas**
A part of #44 
Colgate Total Whitening Gel added

### CODE REVIEW

**Comment by KAUTH** [comment]
@manaswinidas thanks for the contribution!! Please provide a picture of the product's label and not of the package.

**Comment by manaswinidas** [comment]
@KAUTH I am sorry but the ingredients are not present in the site that was provided.

**Comment by KAUTH** [comment]
@manaswinidas yes they are, please look again at http://www.colgatetotal.com/health-benefits/toothpaste-ingredients. There is no possibility that you can't provide a photograph or picture of the ingredients since you copied them from somewhere, therefore there is always a picture or screenshot available when you submit a PR. Thanks!!

**Comment by manaswinidas** [comment]
Yes I found the ingredients @KAUTH but I couldn't find an image along with products as in my previous merged PRs

**Comment by manaswinidas** [comment]
Shall I attach another image of the ingredients @KAUTH? I wrote the ingredients from this screenshot. Shall I attach this instead of that image?
screenshot from 2017-10-18 21-01-00

**Comment by KAUTH** [comment]
@manaswinidas I will put the picture and show you where to get it from, don't worry about it.

**Pull request merged**
