### PR TITLE
Add dr pepper

### PR DESCRIPTION
**Pull request by Justicimo**
Removed DrPepper Zero from this.

### CODE REVIEW

**Comment by Justicimo** [comment]
@KAUTH I also corrected these PRs errors. Let me know if there is anything else I need to fix.

**Comment by KAUTH** [comment]
@Justicimo  there seems to be a problem with merging the file. Could you also change the folder name to Dr Pepper (U.K., 7.10.2017)? Thanks!!

**Comment by KAUTH** [comment]
@Justicimo we are planning a community for this project and we are looking for people to help in achieving this goal.  Your contribution has been very valuable so far and we were wondering if you were interested in being a COMMUNITY LEADER for the U.S.A. Your responsibilities will be finding an average of 3 products / week from the U.S.A. and adding them to Product Crawler. You will review the PRs, merge them and create issues for new products if needed. It is a fairly easy task that requires little time, but careful revewing of the products in order to maintain credibility. We will be waiting for a response, thank you!!

**Comment by Justicimo** [comment]
I appreciate the offer Kauth, but sadly I do not have all that much time to
do this on a weekly basis. However I'd still be glad to stop by and add new
products every once in awhile :)

**Comment by KAUTH** [comment]
@Justicimo once again thank you very much for your contribution!!

**Pull request closed without merging**
