### PR TITLE
Added Toblerone HacktoberFest

### PR DESCRIPTION
**Pull request by s3dna402**
I have added Toblerone for chocolates. I hope it is fine. In my opinion you are doing great thing :) Happy HacktoberFest!

### CODE REVIEW

**Comment by KAUTH** [comment]
@s3dna402 Happy Hacktoberfest and thank you very much!! If you are excited about our project you can download the app as well https://play.google.com/store/apps/details?id=appeiro.productcrawler&hl=en

The txt file looks great, but instead of a picture of the chocolate packaging upload a screenshot of the ingredients from the source website and delete the previous one.

Thank you for your contribution!!

**Comment by s3dna402** [comment]
I uploaded it. I'll check the link that you provided @KAUTH

**Comment by KAUTH** [comment]
@s3dna402  thank you, one more change however, please also put the two files (txt and png) into a folder named with the following format: "Product Name (distributed country(ies), date inserted)" and make your Pull Request

**Comment by s3dna402** [comment]
I just uploaded it 👍

**Comment by KAUTH** [comment]
@s3dna402 it looks great, we will merge the PR soon. Thank you for your time and contribution!!

**Pull request merged**
