### PR TITLE
Added sprite

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by KAUTH** [comment]
@AshtonHarding thanks for your contribution. Could you change the date format on the folder to dd/mm/yy, thanks.

**Comment by ghost** [comment]
Okay fixed up. Sorry about that, I meant to do it that way and I guess my brain swapped it back lol

**Comment by KAUTH** [comment]
@AshtonHarding the text file is now correct. However, one last change, the png doesn't seem to match the info on the website or the txt file. Maybe you should upload a screenshot of the website's info.

**Comment by ghost** [comment]
Okay, I see. I had taken a different screenshot via google because I didn't like their format. I fixed the screenshot and also removed the previous folder (I had apparently created a new folder, instead of just renaming it)

**Pull request merged**
