### PR TITLE
Add Doritos Nacho Cheese Flavored Tortilla Chips

### PR DESCRIPTION
**Pull request by sipark7**

### CODE REVIEW

**Comment by KAUTH** [comment]
@sipark7 thank you very much for your contribution!! Your PR will be reviewed and merged by tommorow.
Check out https://productcrawler.wixsite.com/home, where our database is.
Keep contributing and spread the word.

**Comment by KAUTH** [comment]
@sipark7 don't forget the Product_Name and Product_Type fields in the text file, I added them. Also I think it is 140 cal, not 140 kcal, could you check as well and confirm?
Othen than that great work, thanks for the help!!

**Comment by sipark7** [comment]
Thanks! I thought I had added those fields. My vim was acting up and I should have double checked. Thanks again!

**Comment by sipark7** [comment]
I confirmed that it is 140cal, not 140kcal. You are correct. Thanks!

**Pull request merged**
