### PR TITLE
Add Coca-Cola Classic

### PR DESCRIPTION
**Pull request by exler**
Due to an error with repository cloning I couldn't rename the directory name to Coca-Cola's. Everything else should be in order.

### CODE REVIEW

**Comment by KAUTH** [comment]
@exler the files look fine. However, you should put both the txt file and png file in a folder with the following format: "Product Name (distributed country(ies), date inserted)" and make your Pull Request. 
Thanks a lot!!

**Comment by exler** [comment]
I would really like to do that, but as I said before I cannot clone the repository correctly, because there is a problem with directories filenames.
clone_error

**Comment by KAUTH** [comment]
@exler Maybe you can delete and try to refork the repository.

**Comment by exler** [comment]
I have already done that, I also cannot clone your repository, so it seems like it's either the directory filename's fault or just something wrong with Git on Windows.

**Comment by KAUTH** [comment]
@exler I am sorry but I can't even edit your PR. I am going to have to close it. Thank you for your time!! If you resolve the issue you can repeat the PR.

**Pull request closed without merging**
