### PR TITLE
Added Red Bull Energy Drink

### PR DESCRIPTION
**Pull request by Abhinay1997**
Hi @KAUTH , could you please review this PR?

### CODE REVIEW

**Comment by KAUTH** [comment]
@Abhinay1997  thanks for the contribution!! I am reviewing your PR now.

**Comment by KAUTH** [comment]
@Abhinay1997 everything seems correct. I would like to ask you though, is the label the one that is on the products in the U.S.A., or did you get the photo from the internet? If so, check a Red Bull from the US to see if the info on the labels match. Different countries have sometimes different ingredients on some products. Thanks!!

**Comment by Abhinay1997** [comment]
I got the label from the listing on Amazon.com and all data is from there. I searched for the label on the internet to cross-check the ingredient spellings.

**Comment by Abhinay1997** [comment]
I found a link to the US red bull 8.4 oz pack that matches the data in the .txt : http://energydrink-us.redbull.com/en/red-bull-calories P.S: Thank you for tolerating my typos

**Comment by KAUTH** [comment]
@Abhinay1997 thanks for the last link, it really increases validity. Your contributions are valuable to us!!
To see your contribution live you can also download our app https://play.google.com/store/apps/details?id=appeiro.productcrawler

**Comment by Abhinay1997** [comment]
Thanks @KAUTH , I will make sure to be more diligent with my next pull requests.

**Pull request merged**
