### PR TITLE
add COLGATE TOTAL ADVANCED WHITENING GEL

### PR DESCRIPTION
**Pull request by hhi11**

### CODE REVIEW

**Comment by Iqlaas** [comment]
Hi. Something going on with the deleted files ?

**Comment by KAUTH** [comment]
@Iqlaas that is indeed some weird activity, I'll check it out, thanks!!

**Comment by KAUTH** [comment]
@hhi11 could you add a png file of the ingredients and remove the photo of the packaging of the toothpaste? Thanks for your contribution!!

**Comment by KAUTH** [comment]
@hhi11 Also please change the folder name to "Colgate Total Advanced Whitening Gel (Canada, United States, 3.10.17)". And are you sure that the ingredients are the same for both the U.S.A. and Canada, can that be seen somewhere in the website you have provided as a source?

**Comment by hhi11** [comment]
Hopefully that's better.

**Comment by Iqlaas** [comment]
Hi @hhi11 , seems like you replaced the `README.md` file with your own. Copy from the original repo and paste it into yours, and `push` the `commit` again. The conflicts should be resolved.

**Comment by hhi11** [comment]
ok fixed read me file

**Pull request closed without merging**
